language: rust
rust:
  - nightly

cache: cargo

sudo: required

addons:
  apt:
    packages:
      - libbfd-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - zlib1g-dev
      - binutils-dev
      - libiberty-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz
  - cd kcov-master
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

script:
  - cargo install cargo-kcov
  - cargo build
  - cargo test

after_success:
  - cargo kcov --verbose --coveralls
  - ls -la target/
  - ls -la target/cov
  - ls -la target/kcov
  - ls -la /home/travis/build/kodegenix/kg-tree/target
  - ls -la /home/travis/build/kodegenix/kg-tree/target/cov
  - ls -la /home/travis/build/kodegenix/kg-tree/target/kcov
  - cargo kcov --verbose
  - ls -la target/
  - ls -la target/cov
  - ls -la target/kcov
  - ls -la /home/travis/build/kodegenix/kg-tree/target
  - ls -la /home/travis/build/kodegenix/kg-tree/target/cov
  - ls -la /home/travis/build/kodegenix/kg-tree/target/kcov