language: rust
rust:
  - nightly
  - beta
  - stable

cache: cargo

matrix:
  allow_failures:
    - rust: beta
    - rust: stable

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - zlib1g-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - cargo install cargo-travis || echo "cargo-travis already installed"
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build
  - cargo test
  - cargo coveralls --verbose
