[package]
name = "kg-tree"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
description = """
Generic object tree with Opath query language, similar to XPath.
"""
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Kodegenix/kg-tree"
edition = "2018"

[dependencies]
kg-display = "0.1"
kg-display-derive = "0.1"
kg-diag-derive = "0.1"
kg-diag = "0.1"
kg-io = "0.1"
kg-utils = "0.2"
kg-symbol = "0.1"
lazy_static = "1.1"
backtrace = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.4"
heapsize = "0.4"
heapsize_derive = "0.1"

[dev-dependencies]
assert_approx_eq = "1.0"
tempfile = "3.0"
